TAX_SYSTEM = [
    (1, "REGIME DE L'IMPOT LIBERATOIRE"),
    (2, "REGIME DU SIMPLIE"),
    (3, "REGIME DU REEL"),
    (4, "HORS REGIME D'IMPOSITION")
]

TYPE_PERSON = [
    (1, "PERSONNE PHYSIQUE"),
    (2, "PERSONNE MORALE")
]

ACCEPT_IMAGE = ["jpg", "jpeg", "png", "JPG", "JPEG", "PNG"]

MAX_IMAGE_SIZE = 1000000